### ISSUE TITLE
NodeExpress sample not working with Okta

### ISSUE THREAD

**Issue by ghdna** [ThoughtWorksInc/okta-samples#9]
I've installed node-express example and added the endpoint and cert in the config. But upon accessing localhost:3000, I'm directed to Okta login page, which accepts credentials and redirects to http://localhost:3000/login/callback with error:
`Error: PEM_read_bio_PUBKEY failed at Error (native) at Verify.verify (crypto.js:307:23) at RSASHA256.verifySignature (/Users/john/okta-samples/okta-node-express/node_modules/xml-crypto/lib/signed-xml.js:119:24) at SignedXml.validateSignatureValue (/Users/john/okta-samples/okta-node-express/node_modules/xml-crypto/lib/signed-xml.js:199:20) at SignedXml.checkSignature (/Users/john/okta-samples/okta-node-express/node_modules/xml-crypto/lib/signed-xml.js:187:13) at SAML.validateSignature (/Users/john/okta-samples/okta-node-express/node_modules/passport-saml/lib/passport-saml/saml.js:169:14) at /Users/john/okta-samples/okta-node-express/node_modules/passport-saml/lib/passport-saml/saml.js:192:36 at Parser.<anonymous> (/Users/john/okta-samples/okta-node-express/node_modules/xml2js/lib/xml2js.js:195:18) at emitOne (events.js:90:13) at Parser.emit (events.js:182:7)`

I've the correct certificate in the config file. What else do I need to configure this correctly?

**Comment by viniciusrdacosta** [comment]
Hey @ghdna We had this problem as well, and the solution was remove the `---BEGIN CERTIFICATE ---' and `END CERTIFICATE` from our cert.

**Comment by evillag** [comment]
Still (in 2019 :P) doesn't work. I tried removing the  ---BEGIN CERTIFICATE ---and ---END CERTIFICATE--- from the okta certificate, and didn't solve it.
